[versions]
kotlin = "2.4.0"
waltid = "0.22.0"
waltid-trust-registry = "1.0.0-SNAPSHOT"
kotlinx-coroutines = "1.11.0"
kotlinx-datetime-compat = "0.8.0-0.6.x-compat"
local = "1.0.0-SNAPSHOT"

[libraries]
# walt.id
# required dependencies for running the example project
waltid-crypto = { module = "id.walt.crypto:waltid-crypto", version.ref = "waltid" }
waltid-digital-credentials = { module = "id.walt.credentials:waltid-digital-credentials", version.ref = "waltid" }
waltid-did = { module = "id.walt.did:waltid-did", version.ref = "waltid" }
waltid-x509 = { module = "id.walt.crypto:waltid-x509", version.ref = "local" }
waltid-sdjwt = { module = "id.walt.sdjwt:waltid-sdjwt", version.ref = "waltid" }
waltid-openid4vc = { module = "id.walt.openid4vc:waltid-openid4vc", version.ref = "waltid" }
waltid-verification-policies = { module = "id.walt.policies:waltid-verification-policies", version.ref = "waltid" }
waltid-dif-definitions-parser = { module = "id.walt.dif-definitions-parser:waltid-dif-definitions-parser", version.ref = "waltid" }
waltid-trust-registry = { module = "id.walt.credentials:waltid-trust-registry", version.ref = "waltid-trust-registry" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-datetime-compat = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime-compat" }

# all walt.id dependencies (not required for this project)
waltid-mdoc-credentials = { module = "id.walt.mdoc-credentials:waltid-mdoc-credentials", version.ref = "waltid" }
waltid-service-commons = { module = "id.walt:waltid-service-commons", version.ref = "waltid" }

[bundles]
waltid = ["waltid-crypto", "waltid-x509", "waltid-digital-credentials", "waltid-did", "waltid-sdjwt",
    "waltid-openid4vc", "waltid-verification-policies", "waltid-dif-definitions-parser"]
waltidNotNeeded = ["waltid-mdoc-credentials", "waltid-service-commons"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
